export type Url = typeof urls[keyof typeof urls];
export const urls = {
  akashicPay: 'akashic',
  importAccountUrl: 'import',
  welcome: 'welcome',
  loggedFunction: 'logged-function',
  loggedDeposit: 'logged-deposit',
  sendFunction: 'send-function',
  sendTo: 'send-to',
  sendConfirm: 'send-confirm',
  sendResult: 'send-result',
  nfts: 'nfts',
  nft: 'nft',
  nftTransfer: 'nft-transfer',
  nftTransferResult: 'nft-transfer-result',
  activity: 'activity',
  recoverCode: 'recover-code',
  dashboard: 'dashboard',
  settings: 'settings',
  send: 'send',
  settingsBackup: 'settings-backup',
  settingsDelete: 'settings-delete',
  settingsNaming: 'settings-naming',
  settingsVersion: 'settings-version',
  changePassword: 'change-password',
  changePasswordConfirm: 'change-pass-confirm',
  secret: 'create-wallet-secret',
  error: 'error',
  us2: 'us2',
  createWalletPassword: 'create-wallet-password',
  importWalletPassword: 'import-wallet-password',
  walletCreated: 'wallet-created',
  secretConfirm: 'secret-confirm',
  keyPairImport: 'keyPairImport',
  secretPhraseImport: 'secret-phrase-import',
  selectImportMethod: 'select-import-method',
  importSuccess: 'import-success',
  changePasswordAfterImport: 'change-password-after-import',
  manageAccounts: 'manage-account',
  migrateWalletSecret: 'migrate-wallet-secret',
  migrateWalletSecretConfirm: 'migrate-secret-confirm',
  migrateWalletOldPassword: 'migrate-wallet-old-password',
  migrateWalletPassword: 'migrate-wallet-password',
  migrateWalletNotice: 'migrate-wallet-notice',
  migrateWalletComplete: 'migrate-wallet-complete',
} as const;

export const createWalletUrls = [
  urls.createWalletPassword,
  urls.secret,
  urls.secretConfirm,
];
export const importWalletUrls = [
  urls.importWalletPassword,
  urls.keyPairImport,
  urls.secretPhraseImport,
  urls.selectImportMethod,
];
export const migrateWalletUrls = [
  urls.migrateWalletNotice,
  urls.migrateWalletSecret,
  urls.migrateWalletSecretConfirm,
  urls.migrateWalletOldPassword,
  urls.migrateWalletPassword,
];
